import Header from '@/components/Header';
import Footer from '@/components/Footer';
import './globals.css';
import '../lib/fontAwesome';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="light:bg-white dark:bg-customDark flex flex-col min-h-screen">
        <Header />
        <main className="container flex-grow mx-auto p-4">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
