name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY_BASE64: ${{ secrets.SSH_PRIVATE_KEY_BASE64 }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: |
          echo "Setting up SSH"
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "Testing SSH connection to $EC2_USER@$EC2_HOST"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST "echo 'SSH connection successful'"
          if [ $? -ne 0 ]; then
            echo "SSH connection failed"
            exit 1
          fi

          echo "Removing old files from /var/www/html"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST "sudo rm -rf /var/www/html/*"

          echo "Copying new files to /var/www/html"
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./* $EC2_USER@$EC2_HOST:/var/www/html

          echo "Setting up environment variables"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST "
            sudo rm -f /var/www/html/.env &&
            echo SMTP_HOST=smtp.gmail.com | sudo tee -a /var/www/html/.env &&
            echo SMTP_PORT=587 | sudo tee -a /var/www/html/.env &&
            echo SMTP_SECURE=false | sudo tee -a /var/www/html/.env &&
            echo SMTP_USER=neil.mccaffrey83@gmail.com | sudo tee -a /var/www/html/.env &&
            echo SMTP_PASS=${SMTP_PASS} | sudo tee -a /var/www/html/.env &&
            echo RECEIVER_EMAIL=neil.mccaffrey83@gmail.com | sudo tee -a /var/www/html/.env
          "

          echo "Installing dependencies and starting application"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST "
            cd /var/www/html && 
            sudo rm -rf node_modules package-lock.json &&
            npm install &&
            npm run build &&
            sudo npm install -g pm2 &&
            pm2 restart all || pm2 start npm --name 'app' -- start
          "
